### ISSUE TITLE
get_clusters.py attempting to load non-existent classifier

### ISSUE THREAD

**Issue by torridgristle** [terrybroad/network-bending#2]
I've run `!python generate_activation_training_set.py --size 512 --num_samples 128 --truncation 0.5 --ckpt afhqcat.pt` and I've run `!python train_classifiers.py` and now I'm trying to run `!python get_clusters.py --n_layers 8 --truncation 0.5 --ckpt afhqcat.pt` and it'll tell me this:
```
get clusters
  0% 0/8 [00:00<?, ?it/s]I0

100% 512/512 [00:00<00:00, 1997659.21it/s]
I1

100% 512/512 [00:00<00:00, 2246321.81it/s]
I2

100% 512/512 [00:00<00:00, 2265278.11it/s]
I3

100% 512/512 [00:00<00:00, 2251031.08it/s]
I4

100% 512/512 [00:00<00:00, 2213900.67it/s]
I5

100% 512/512 [00:00<00:00, 2301697.37it/s]
I6

100% 512/512 [00:00<00:00, 2248673.98it/s]
I7

100% 512/512 [00:00<00:00, 2241632.20it/s]
100% 8/8 [00:00<00:00, 2695.78it/s]
  0% 0/1000 [00:00<?, ?it/s]processing sample: 0
  0% 0/1000 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "get_clusters.py", line 242, in <module>
    get_clusters_from_generated_average(args, g_ema, device, mean_latent, transform_dict_list, yaml_config, layer_channel_dims)
  File "get_clusters.py", line 120, in get_clusters_from_generated_average
    classifier_state_dict = torch.load(classifier_str)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/classifiers/9/classifier9_final.pt'
```
Since I told it 8 layers it shouldn't try to open a classifier for a 9th layer, but I can't seem to get it to not do this when I adjust the true_index = index+1 parts. I'm at a complete loss with how to make it not try to open something that doesn't exist.

**Comment by terrybroad** [comment]
Apologies, there was an assumption in the code that you would always be calculating clusters for all the layers in the model. I have pushed an update in 78da602 that corrects for this to instead strictly use the `num_layers` parameter. This should hopefully fix your issue.
