### ISSUE TITLE
batch process (--sample 2 or more)

### ISSUE THREAD

**Issue by naotokui** [terrybroad/network-bending#3]
I got the following error when I set the argument `--sample` other than 1, say 4, and run the `generate.py` script. (I used the StyleGAN model `stylegan2-ffhq-config-f.pt`) 
Everything works well with --sample 1. Do you have any idea how I can solve this issue? 
Thanks in advance!

```Traceback (most recent call last):
  File "generate.py", line 109, in <module>
    generate(args, g_ema, device, mean_latent, yaml_config, cluster_config, layer_channel_dims)
  File "generate.py", line 18, in generate
    sample, _ = g_ema([sample_z], truncation=args.truncation, truncation_latent=mean_latent, transform_dict_list=t_dict_list)
  File "/home/nao/anaconda3/envs/aidj3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nao/git/network-bending-org/model.py", line 546, in forward
    skip = to_rgb(out, latent[:, i + 2], skip)
  File "/home/nao/anaconda3/envs/aidj3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nao/git/network-bending-org/model.py", line 358, in forward
    out = self.conv(input, style)
  File "/home/nao/anaconda3/envs/aidj3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nao/git/network-bending-org/model.py", line 240, in forward
    style = self.modulation(style).view(batch, 1, in_channel, 1, 1)
RuntimeError: shape '[1, 1, 512, 1, 1]' is invalid for input of size 2048 ```

**Comment by terrybroad** [comment]
Ah yes so this is because the way the network bending code operates for dividing the activation maps into individual matricies (for processing with OpenCV), it assumes there is only a batch size of one. 

To generate multiple samples you can use the flag `--pics` instead, which generated them sequentially instead of all in one go.
